// Script to generate ABI and address files from Hardhat deployments
// This script reads from ../contracts/deployments/ and generates TypeScript files

import { readFileSync, writeFileSync, existsSync, readdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const contractsDir = join(__dirname, "../../contracts");
const deploymentsDir = join(contractsDir, "deployments");
const abiDir = join(__dirname, "../abi");

function generateABIFiles() {
  if (!existsSync(deploymentsDir)) {
    console.log("Deployments directory not found. Run 'npx hardhat deploy' first.");
    return;
  }

  const networks = readdirSync(deploymentsDir);
  const addresses = {};
  let abi = null;

  for (const network of networks) {
    const networkDir = join(deploymentsDir, network);
    if (!existsSync(networkDir)) continue;

    const files = readdirSync(networkDir);
    const payrollFile = files.find(f => f.startsWith("PayrollDapp") && f.endsWith(".json"));

    if (payrollFile) {
      try {
        const filePath = join(networkDir, payrollFile);
        const deployment = JSON.parse(readFileSync(filePath, "utf-8"));

        if (deployment.address && deployment.address !== "0x0000000000000000000000000000000000000000") {
          const chainId = getChainId(network);
          // Use chainId as key to ensure proper mapping (consistent with usePayrollDapp.tsx which uses chainId.toString())
          const addressKey = chainId > 0 ? chainId.toString() : network;
          addresses[addressKey] = {
            address: deployment.address,
            chainId: chainId,
            chainName: network,
          };
          console.log(`Found deployment for ${network} (chainId: ${chainId}): ${deployment.address}`);
        }

        if (!abi && deployment.abi) {
          abi = deployment.abi;
        }
      } catch (error) {
        console.warn(`Skipping ${network}: ${error.message}`);
        continue;
      }
    } else {
      console.log(`No PayrollDapp deployment found for ${network}, skipping...`);
    }
  }

  // Generate addresses file
  const addressesContent = `// This file is auto-generated by genabi.mjs script
// It contains contract addresses for different networks
// Addresses are mapped using chainId as key (e.g., "31337" for localhost, "11155111" for sepolia)

export const PayrollDappAddresses: Record<string, { address: \`0x\${string}\`; chainId: number; chainName?: string }> = ${JSON.stringify(addresses, null, 2)};
`;
  writeFileSync(join(abiDir, "PayrollDappAddresses.ts"), addressesContent);

  // Generate ABI file
  if (abi) {
    const abiContent = `// This file is auto-generated by genabi.mjs script
// It contains the ABI for PayrollDapp contract

export const PayrollDappABI = {
  abi: ${JSON.stringify(abi, null, 2)} as const,
};
`;
    writeFileSync(join(abiDir, "PayrollDappABI.ts"), abiContent);
    console.log("ABI file generated successfully!");
  } else {
    console.warn("No ABI found in deployments. ABI file not generated.");
  }

  if (Object.keys(addresses).length > 0) {
    console.log(`Addresses file generated successfully with ${Object.keys(addresses).length} network(s)!`);
  } else {
    console.warn("No contract addresses found. Addresses file generated with empty object.");
  }
}

function getChainId(network) {
  const chainIdMap = {
    localhost: 31337,
    hardhat: 31337,
    sepolia: 11155111,
    mainnet: 1,
  };
  return chainIdMap[network] || 0;
}

generateABIFiles();

