// This file is auto-generated by genabi.mjs script
// It contains contract addresses for different networks
// Addresses are mapped using chainId as key (e.g., "31337" for localhost, "11155111" for sepolia)

export const PayrollDappAddresses: Record<string, { address: `0x${string}`; chainId: number; chainName?: string }> = {
  "11155111": {
    "address": "0x8b153F01b52a9694f2D6D7C6Ee2A366c448C592d",
    "chainId": 11155111,
    "chainName": "sepolia"
  }
};
