/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PayrollDappInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEPARTMENT_MANAGER_ROLE"
      | "EMPLOYEE_ROLE"
      | "FINANCE_ADMIN_ROLE"
      | "SUPER_ADMIN_ROLE"
      | "addDepartmentNames"
      | "addEmployee"
      | "addEmployeeAddresses"
      | "approveSalaryAdjustment"
      | "assignRole"
      | "batchGrantBonus"
      | "bonusRecords"
      | "departmentEmployees"
      | "departmentNameList"
      | "employeeAddressList"
      | "employeeDepartments"
      | "employees"
      | "executeSalaryAdjustment"
      | "getAllDepartmentNames"
      | "getAllEmployeeAddresses"
      | "getAuditStatistics"
      | "getBonusRecordCount"
      | "getDepartmentEncryptedPayroll"
      | "getDepartmentNameCount"
      | "getEmployeeAddressCount"
      | "getEncryptedAverageSalary"
      | "getEncryptedBonus"
      | "getEncryptedSalary"
      | "getPaymentInterval"
      | "getPaymentRecordCount"
      | "getRoleChangeRecordCount"
      | "getSalaryAdjustmentCount"
      | "getSalaryAdjustmentRequestCount"
      | "getTotalEmployees"
      | "getTotalEncryptedBonuses"
      | "getTotalEncryptedPayroll"
      | "getUserRole"
      | "grantBonus"
      | "isDepartmentNameRegistered"
      | "isEmployeeAddressRegistered"
      | "lastPaymentDate"
      | "paymentInterval"
      | "paymentRecords"
      | "processEmployeePayment"
      | "processPayments"
      | "protocolId"
      | "removeDepartmentName"
      | "removeEmployee"
      | "removeEmployeeAddress"
      | "requestSalaryAdjustment"
      | "revokeRole"
      | "roleChangeRecords"
      | "roles"
      | "salaryAdjustmentRequests"
      | "salaryAdjustments"
      | "setPaymentInterval"
      | "superAdmin"
      | "totalEmployees"
      | "totalEncryptedBonuses"
      | "totalEncryptedPayroll"
      | "updateEmployeeDepartment"
      | "updateSalary"
      | "userRoles"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchBonusGranted"
      | "BonusGranted"
      | "DepartmentNameAdded"
      | "DepartmentNameRemoved"
      | "DepartmentUpdated"
      | "EmployeeAdded"
      | "EmployeeAddressAdded"
      | "EmployeeAddressRemoved"
      | "EmployeeRemoved"
      | "PaymentProcessed"
      | "RoleAssigned"
      | "RoleRevoked"
      | "SalaryAdjustmentApproved"
      | "SalaryAdjustmentExecuted"
      | "SalaryAdjustmentRequested"
      | "SalaryUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEPARTMENT_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMPLOYEE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FINANCE_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUPER_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addDepartmentNames",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addEmployee",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addEmployeeAddresses",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "approveSalaryAdjustment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignRole",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchGrantBonus",
    values: [AddressLike[], BytesLike[], BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "bonusRecords",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "departmentEmployees",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "departmentNameList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "employeeAddressList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "employeeDepartments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "employees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSalaryAdjustment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllDepartmentNames",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEmployeeAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditStatistics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBonusRecordCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepartmentEncryptedPayroll",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepartmentNameCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployeeAddressCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedAverageSalary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBonus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedSalary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentRecordCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleChangeRecordCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSalaryAdjustmentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSalaryAdjustmentRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalEmployees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalEncryptedBonuses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalEncryptedPayroll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantBonus",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDepartmentNameRegistered",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isEmployeeAddressRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPaymentDate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "paymentInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "paymentRecords",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processEmployeePayment",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processPayments",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeDepartmentName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeEmployeeAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestSalaryAdjustment",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roleChangeRecords",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "roles", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "salaryAdjustmentRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "salaryAdjustments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "superAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalEmployees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalEncryptedBonuses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalEncryptedPayroll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateEmployeeDepartment",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSalary",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userRoles",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEPARTMENT_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMPLOYEE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FINANCE_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUPER_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDepartmentNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addEmployeeAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveSalaryAdjustment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assignRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchGrantBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bonusRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "departmentEmployees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "departmentNameList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "employeeAddressList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "employeeDepartments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "employees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeSalaryAdjustment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllDepartmentNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEmployeeAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditStatistics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBonusRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepartmentEncryptedPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepartmentNameCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployeeAddressCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedAverageSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleChangeRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSalaryAdjustmentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSalaryAdjustmentRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalEmployees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalEncryptedBonuses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalEncryptedPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantBonus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDepartmentNameRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEmployeeAddressRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPaymentDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processEmployeePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeDepartmentName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeEmployeeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSalaryAdjustment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roleChangeRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "salaryAdjustmentRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "salaryAdjustments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "superAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalEmployees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEncryptedBonuses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEncryptedPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEmployeeDepartment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userRoles", data: BytesLike): Result;
}

export namespace BatchBonusGrantedEvent {
  export type InputTuple = [count: BigNumberish, reasonHash: BytesLike];
  export type OutputTuple = [count: bigint, reasonHash: string];
  export interface OutputObject {
    count: bigint;
    reasonHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BonusGrantedEvent {
  export type InputTuple = [employee: AddressLike, reasonHash: BytesLike];
  export type OutputTuple = [employee: string, reasonHash: string];
  export interface OutputObject {
    employee: string;
    reasonHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepartmentNameAddedEvent {
  export type InputTuple = [departmentName: string];
  export type OutputTuple = [departmentName: string];
  export interface OutputObject {
    departmentName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepartmentNameRemovedEvent {
  export type InputTuple = [departmentName: string];
  export type OutputTuple = [departmentName: string];
  export interface OutputObject {
    departmentName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepartmentUpdatedEvent {
  export type InputTuple = [
    employee: AddressLike,
    oldDepartment: BytesLike,
    newDepartment: BytesLike
  ];
  export type OutputTuple = [
    employee: string,
    oldDepartment: string,
    newDepartment: string
  ];
  export interface OutputObject {
    employee: string;
    oldDepartment: string;
    newDepartment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeAddedEvent {
  export type InputTuple = [employee: AddressLike, departmentHash: BytesLike];
  export type OutputTuple = [employee: string, departmentHash: string];
  export interface OutputObject {
    employee: string;
    departmentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeAddressAddedEvent {
  export type InputTuple = [employeeAddress: AddressLike];
  export type OutputTuple = [employeeAddress: string];
  export interface OutputObject {
    employeeAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeAddressRemovedEvent {
  export type InputTuple = [employeeAddress: AddressLike];
  export type OutputTuple = [employeeAddress: string];
  export interface OutputObject {
    employeeAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeRemovedEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentProcessedEvent {
  export type InputTuple = [employee: AddressLike, paymentTypeHash: BytesLike];
  export type OutputTuple = [employee: string, paymentTypeHash: string];
  export interface OutputObject {
    employee: string;
    paymentTypeHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAssignedEvent {
  export type InputTuple = [user: AddressLike, role: BytesLike];
  export type OutputTuple = [user: string, role: string];
  export interface OutputObject {
    user: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [user: AddressLike, role: BytesLike];
  export type OutputTuple = [user: string, role: string];
  export interface OutputObject {
    user: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryAdjustmentApprovedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryAdjustmentExecutedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryAdjustmentRequestedEvent {
  export type InputTuple = [
    employee: AddressLike,
    reasonHash: BytesLike,
    requestId: BigNumberish
  ];
  export type OutputTuple = [
    employee: string,
    reasonHash: string,
    requestId: bigint
  ];
  export interface OutputObject {
    employee: string;
    reasonHash: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryUpdatedEvent {
  export type InputTuple = [employee: AddressLike, reasonHash: BytesLike];
  export type OutputTuple = [employee: string, reasonHash: string];
  export interface OutputObject {
    employee: string;
    reasonHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PayrollDapp extends BaseContract {
  connect(runner?: ContractRunner | null): PayrollDapp;
  waitForDeployment(): Promise<this>;

  interface: PayrollDappInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEPARTMENT_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  EMPLOYEE_ROLE: TypedContractMethod<[], [string], "view">;

  FINANCE_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  SUPER_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  addDepartmentNames: TypedContractMethod<
    [names: string[]],
    [void],
    "nonpayable"
  >;

  addEmployee: TypedContractMethod<
    [
      employeeAddress: AddressLike,
      departmentHash: BytesLike,
      encryptedSalary: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  addEmployeeAddresses: TypedContractMethod<
    [addresses: AddressLike[]],
    [void],
    "nonpayable"
  >;

  approveSalaryAdjustment: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  assignRole: TypedContractMethod<
    [user: AddressLike, role: BytesLike],
    [void],
    "nonpayable"
  >;

  batchGrantBonus: TypedContractMethod<
    [
      employeeAddresses: AddressLike[],
      encryptedBonuses: BytesLike[],
      reasonHash: BytesLike,
      inputProofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  bonusRecords: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        employeeAddress: string;
        encryptedBonus: string;
        reasonHash: string;
        grantedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  departmentEmployees: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  departmentNameList: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  employeeAddressList: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  employeeDepartments: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  employees: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, boolean, bigint] & {
        employeeAddress: string;
        departmentHash: string;
        encryptedSalary: string;
        encryptedBonus: string;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  executeSalaryAdjustment: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllDepartmentNames: TypedContractMethod<[], [string[]], "view">;

  getAllEmployeeAddresses: TypedContractMethod<[], [string[]], "view">;

  getAuditStatistics: TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint] & {
        totalPayroll: string;
        totalBonuses: string;
        totalEmployees_: bigint;
        totalAdjustments: bigint;
        totalBonusRecords: bigint;
      }
    ],
    "nonpayable"
  >;

  getBonusRecordCount: TypedContractMethod<[], [bigint], "view">;

  getDepartmentEncryptedPayroll: TypedContractMethod<
    [departmentHash: BytesLike],
    [string],
    "nonpayable"
  >;

  getDepartmentNameCount: TypedContractMethod<[], [bigint], "view">;

  getEmployeeAddressCount: TypedContractMethod<[], [bigint], "view">;

  getEncryptedAverageSalary: TypedContractMethod<[], [string], "nonpayable">;

  getEncryptedBonus: TypedContractMethod<
    [employeeAddress: AddressLike],
    [string],
    "nonpayable"
  >;

  getEncryptedSalary: TypedContractMethod<
    [employeeAddress: AddressLike],
    [string],
    "nonpayable"
  >;

  getPaymentInterval: TypedContractMethod<[], [bigint], "view">;

  getPaymentRecordCount: TypedContractMethod<[], [bigint], "view">;

  getRoleChangeRecordCount: TypedContractMethod<[], [bigint], "view">;

  getSalaryAdjustmentCount: TypedContractMethod<[], [bigint], "view">;

  getSalaryAdjustmentRequestCount: TypedContractMethod<[], [bigint], "view">;

  getTotalEmployees: TypedContractMethod<[], [bigint], "view">;

  getTotalEncryptedBonuses: TypedContractMethod<[], [string], "nonpayable">;

  getTotalEncryptedPayroll: TypedContractMethod<[], [string], "nonpayable">;

  getUserRole: TypedContractMethod<[user: AddressLike], [string], "view">;

  grantBonus: TypedContractMethod<
    [
      employeeAddress: AddressLike,
      encryptedBonus: BytesLike,
      reasonHash: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  isDepartmentNameRegistered: TypedContractMethod<
    [arg0: string],
    [boolean],
    "view"
  >;

  isEmployeeAddressRegistered: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  lastPaymentDate: TypedContractMethod<[], [bigint], "view">;

  paymentInterval: TypedContractMethod<[], [bigint], "view">;

  paymentRecords: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        employeeAddress: string;
        encryptedAmount: string;
        paymentTypeHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  processEmployeePayment: TypedContractMethod<
    [
      employeeAddress: AddressLike,
      encryptedAmount: BytesLike,
      paymentTypeHash: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  processPayments: TypedContractMethod<[], [void], "nonpayable">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  removeDepartmentName: TypedContractMethod<
    [departmentName: string],
    [void],
    "nonpayable"
  >;

  removeEmployee: TypedContractMethod<
    [employeeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  removeEmployeeAddress: TypedContractMethod<
    [employeeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  requestSalaryAdjustment: TypedContractMethod<
    [
      employeeAddress: AddressLike,
      requestedEncryptedSalary: BytesLike,
      reasonHash: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  roleChangeRecords: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        user: string;
        previousRole: string;
        newRole: string;
        changedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  roles: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  salaryAdjustmentRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, boolean, boolean] & {
        employeeAddress: string;
        requestedSalary: string;
        reasonHash: string;
        requestedBy: string;
        timestamp: bigint;
        approved: boolean;
        executed: boolean;
      }
    ],
    "view"
  >;

  salaryAdjustments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, string, bigint] & {
        employeeAddress: string;
        previousSalary: string;
        newSalary: string;
        reasonHash: string;
        adjustedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  setPaymentInterval: TypedContractMethod<
    [interval: BigNumberish],
    [void],
    "nonpayable"
  >;

  superAdmin: TypedContractMethod<[], [string], "view">;

  totalEmployees: TypedContractMethod<[], [bigint], "view">;

  totalEncryptedBonuses: TypedContractMethod<[], [string], "view">;

  totalEncryptedPayroll: TypedContractMethod<[], [string], "view">;

  updateEmployeeDepartment: TypedContractMethod<
    [employeeAddress: AddressLike, newDepartmentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  updateSalary: TypedContractMethod<
    [
      employeeAddress: AddressLike,
      newEncryptedSalary: BytesLike,
      reasonHash: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  userRoles: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEPARTMENT_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EMPLOYEE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FINANCE_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SUPER_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addDepartmentNames"
  ): TypedContractMethod<[names: string[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addEmployee"
  ): TypedContractMethod<
    [
      employeeAddress: AddressLike,
      departmentHash: BytesLike,
      encryptedSalary: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addEmployeeAddresses"
  ): TypedContractMethod<[addresses: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveSalaryAdjustment"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignRole"
  ): TypedContractMethod<
    [user: AddressLike, role: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchGrantBonus"
  ): TypedContractMethod<
    [
      employeeAddresses: AddressLike[],
      encryptedBonuses: BytesLike[],
      reasonHash: BytesLike,
      inputProofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bonusRecords"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        employeeAddress: string;
        encryptedBonus: string;
        reasonHash: string;
        grantedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "departmentEmployees"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "departmentNameList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "employeeAddressList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "employeeDepartments"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "employees"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, boolean, bigint] & {
        employeeAddress: string;
        departmentHash: string;
        encryptedSalary: string;
        encryptedBonus: string;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeSalaryAdjustment"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllDepartmentNames"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllEmployeeAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAuditStatistics"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint] & {
        totalPayroll: string;
        totalBonuses: string;
        totalEmployees_: bigint;
        totalAdjustments: bigint;
        totalBonusRecords: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBonusRecordCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDepartmentEncryptedPayroll"
  ): TypedContractMethod<[departmentHash: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getDepartmentNameCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEmployeeAddressCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedAverageSalary"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedBonus"
  ): TypedContractMethod<
    [employeeAddress: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedSalary"
  ): TypedContractMethod<
    [employeeAddress: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPaymentInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPaymentRecordCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleChangeRecordCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSalaryAdjustmentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSalaryAdjustmentRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalEmployees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalEncryptedBonuses"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getTotalEncryptedPayroll"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getUserRole"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantBonus"
  ): TypedContractMethod<
    [
      employeeAddress: AddressLike,
      encryptedBonus: BytesLike,
      reasonHash: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isDepartmentNameRegistered"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "isEmployeeAddressRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastPaymentDate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "paymentInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "paymentRecords"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        employeeAddress: string;
        encryptedAmount: string;
        paymentTypeHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "processEmployeePayment"
  ): TypedContractMethod<
    [
      employeeAddress: AddressLike,
      encryptedAmount: BytesLike,
      paymentTypeHash: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processPayments"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeDepartmentName"
  ): TypedContractMethod<[departmentName: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeEmployee"
  ): TypedContractMethod<[employeeAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeEmployeeAddress"
  ): TypedContractMethod<[employeeAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestSalaryAdjustment"
  ): TypedContractMethod<
    [
      employeeAddress: AddressLike,
      requestedEncryptedSalary: BytesLike,
      reasonHash: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "roleChangeRecords"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        user: string;
        previousRole: string;
        newRole: string;
        changedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "roles"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "salaryAdjustmentRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, boolean, boolean] & {
        employeeAddress: string;
        requestedSalary: string;
        reasonHash: string;
        requestedBy: string;
        timestamp: bigint;
        approved: boolean;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "salaryAdjustments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, string, bigint] & {
        employeeAddress: string;
        previousSalary: string;
        newSalary: string;
        reasonHash: string;
        adjustedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setPaymentInterval"
  ): TypedContractMethod<[interval: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "superAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalEmployees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalEncryptedBonuses"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalEncryptedPayroll"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateEmployeeDepartment"
  ): TypedContractMethod<
    [employeeAddress: AddressLike, newDepartmentHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSalary"
  ): TypedContractMethod<
    [
      employeeAddress: AddressLike,
      newEncryptedSalary: BytesLike,
      reasonHash: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userRoles"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "BatchBonusGranted"
  ): TypedContractEvent<
    BatchBonusGrantedEvent.InputTuple,
    BatchBonusGrantedEvent.OutputTuple,
    BatchBonusGrantedEvent.OutputObject
  >;
  getEvent(
    key: "BonusGranted"
  ): TypedContractEvent<
    BonusGrantedEvent.InputTuple,
    BonusGrantedEvent.OutputTuple,
    BonusGrantedEvent.OutputObject
  >;
  getEvent(
    key: "DepartmentNameAdded"
  ): TypedContractEvent<
    DepartmentNameAddedEvent.InputTuple,
    DepartmentNameAddedEvent.OutputTuple,
    DepartmentNameAddedEvent.OutputObject
  >;
  getEvent(
    key: "DepartmentNameRemoved"
  ): TypedContractEvent<
    DepartmentNameRemovedEvent.InputTuple,
    DepartmentNameRemovedEvent.OutputTuple,
    DepartmentNameRemovedEvent.OutputObject
  >;
  getEvent(
    key: "DepartmentUpdated"
  ): TypedContractEvent<
    DepartmentUpdatedEvent.InputTuple,
    DepartmentUpdatedEvent.OutputTuple,
    DepartmentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeAdded"
  ): TypedContractEvent<
    EmployeeAddedEvent.InputTuple,
    EmployeeAddedEvent.OutputTuple,
    EmployeeAddedEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeAddressAdded"
  ): TypedContractEvent<
    EmployeeAddressAddedEvent.InputTuple,
    EmployeeAddressAddedEvent.OutputTuple,
    EmployeeAddressAddedEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeAddressRemoved"
  ): TypedContractEvent<
    EmployeeAddressRemovedEvent.InputTuple,
    EmployeeAddressRemovedEvent.OutputTuple,
    EmployeeAddressRemovedEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeRemoved"
  ): TypedContractEvent<
    EmployeeRemovedEvent.InputTuple,
    EmployeeRemovedEvent.OutputTuple,
    EmployeeRemovedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentProcessed"
  ): TypedContractEvent<
    PaymentProcessedEvent.InputTuple,
    PaymentProcessedEvent.OutputTuple,
    PaymentProcessedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAssigned"
  ): TypedContractEvent<
    RoleAssignedEvent.InputTuple,
    RoleAssignedEvent.OutputTuple,
    RoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SalaryAdjustmentApproved"
  ): TypedContractEvent<
    SalaryAdjustmentApprovedEvent.InputTuple,
    SalaryAdjustmentApprovedEvent.OutputTuple,
    SalaryAdjustmentApprovedEvent.OutputObject
  >;
  getEvent(
    key: "SalaryAdjustmentExecuted"
  ): TypedContractEvent<
    SalaryAdjustmentExecutedEvent.InputTuple,
    SalaryAdjustmentExecutedEvent.OutputTuple,
    SalaryAdjustmentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "SalaryAdjustmentRequested"
  ): TypedContractEvent<
    SalaryAdjustmentRequestedEvent.InputTuple,
    SalaryAdjustmentRequestedEvent.OutputTuple,
    SalaryAdjustmentRequestedEvent.OutputObject
  >;
  getEvent(
    key: "SalaryUpdated"
  ): TypedContractEvent<
    SalaryUpdatedEvent.InputTuple,
    SalaryUpdatedEvent.OutputTuple,
    SalaryUpdatedEvent.OutputObject
  >;

  filters: {
    "BatchBonusGranted(uint256,bytes32)": TypedContractEvent<
      BatchBonusGrantedEvent.InputTuple,
      BatchBonusGrantedEvent.OutputTuple,
      BatchBonusGrantedEvent.OutputObject
    >;
    BatchBonusGranted: TypedContractEvent<
      BatchBonusGrantedEvent.InputTuple,
      BatchBonusGrantedEvent.OutputTuple,
      BatchBonusGrantedEvent.OutputObject
    >;

    "BonusGranted(address,bytes32)": TypedContractEvent<
      BonusGrantedEvent.InputTuple,
      BonusGrantedEvent.OutputTuple,
      BonusGrantedEvent.OutputObject
    >;
    BonusGranted: TypedContractEvent<
      BonusGrantedEvent.InputTuple,
      BonusGrantedEvent.OutputTuple,
      BonusGrantedEvent.OutputObject
    >;

    "DepartmentNameAdded(string)": TypedContractEvent<
      DepartmentNameAddedEvent.InputTuple,
      DepartmentNameAddedEvent.OutputTuple,
      DepartmentNameAddedEvent.OutputObject
    >;
    DepartmentNameAdded: TypedContractEvent<
      DepartmentNameAddedEvent.InputTuple,
      DepartmentNameAddedEvent.OutputTuple,
      DepartmentNameAddedEvent.OutputObject
    >;

    "DepartmentNameRemoved(string)": TypedContractEvent<
      DepartmentNameRemovedEvent.InputTuple,
      DepartmentNameRemovedEvent.OutputTuple,
      DepartmentNameRemovedEvent.OutputObject
    >;
    DepartmentNameRemoved: TypedContractEvent<
      DepartmentNameRemovedEvent.InputTuple,
      DepartmentNameRemovedEvent.OutputTuple,
      DepartmentNameRemovedEvent.OutputObject
    >;

    "DepartmentUpdated(address,bytes32,bytes32)": TypedContractEvent<
      DepartmentUpdatedEvent.InputTuple,
      DepartmentUpdatedEvent.OutputTuple,
      DepartmentUpdatedEvent.OutputObject
    >;
    DepartmentUpdated: TypedContractEvent<
      DepartmentUpdatedEvent.InputTuple,
      DepartmentUpdatedEvent.OutputTuple,
      DepartmentUpdatedEvent.OutputObject
    >;

    "EmployeeAdded(address,bytes32)": TypedContractEvent<
      EmployeeAddedEvent.InputTuple,
      EmployeeAddedEvent.OutputTuple,
      EmployeeAddedEvent.OutputObject
    >;
    EmployeeAdded: TypedContractEvent<
      EmployeeAddedEvent.InputTuple,
      EmployeeAddedEvent.OutputTuple,
      EmployeeAddedEvent.OutputObject
    >;

    "EmployeeAddressAdded(address)": TypedContractEvent<
      EmployeeAddressAddedEvent.InputTuple,
      EmployeeAddressAddedEvent.OutputTuple,
      EmployeeAddressAddedEvent.OutputObject
    >;
    EmployeeAddressAdded: TypedContractEvent<
      EmployeeAddressAddedEvent.InputTuple,
      EmployeeAddressAddedEvent.OutputTuple,
      EmployeeAddressAddedEvent.OutputObject
    >;

    "EmployeeAddressRemoved(address)": TypedContractEvent<
      EmployeeAddressRemovedEvent.InputTuple,
      EmployeeAddressRemovedEvent.OutputTuple,
      EmployeeAddressRemovedEvent.OutputObject
    >;
    EmployeeAddressRemoved: TypedContractEvent<
      EmployeeAddressRemovedEvent.InputTuple,
      EmployeeAddressRemovedEvent.OutputTuple,
      EmployeeAddressRemovedEvent.OutputObject
    >;

    "EmployeeRemoved(address)": TypedContractEvent<
      EmployeeRemovedEvent.InputTuple,
      EmployeeRemovedEvent.OutputTuple,
      EmployeeRemovedEvent.OutputObject
    >;
    EmployeeRemoved: TypedContractEvent<
      EmployeeRemovedEvent.InputTuple,
      EmployeeRemovedEvent.OutputTuple,
      EmployeeRemovedEvent.OutputObject
    >;

    "PaymentProcessed(address,bytes32)": TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;
    PaymentProcessed: TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;

    "RoleAssigned(address,bytes32)": TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;
    RoleAssigned: TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;

    "RoleRevoked(address,bytes32)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SalaryAdjustmentApproved(uint256)": TypedContractEvent<
      SalaryAdjustmentApprovedEvent.InputTuple,
      SalaryAdjustmentApprovedEvent.OutputTuple,
      SalaryAdjustmentApprovedEvent.OutputObject
    >;
    SalaryAdjustmentApproved: TypedContractEvent<
      SalaryAdjustmentApprovedEvent.InputTuple,
      SalaryAdjustmentApprovedEvent.OutputTuple,
      SalaryAdjustmentApprovedEvent.OutputObject
    >;

    "SalaryAdjustmentExecuted(uint256)": TypedContractEvent<
      SalaryAdjustmentExecutedEvent.InputTuple,
      SalaryAdjustmentExecutedEvent.OutputTuple,
      SalaryAdjustmentExecutedEvent.OutputObject
    >;
    SalaryAdjustmentExecuted: TypedContractEvent<
      SalaryAdjustmentExecutedEvent.InputTuple,
      SalaryAdjustmentExecutedEvent.OutputTuple,
      SalaryAdjustmentExecutedEvent.OutputObject
    >;

    "SalaryAdjustmentRequested(address,bytes32,uint256)": TypedContractEvent<
      SalaryAdjustmentRequestedEvent.InputTuple,
      SalaryAdjustmentRequestedEvent.OutputTuple,
      SalaryAdjustmentRequestedEvent.OutputObject
    >;
    SalaryAdjustmentRequested: TypedContractEvent<
      SalaryAdjustmentRequestedEvent.InputTuple,
      SalaryAdjustmentRequestedEvent.OutputTuple,
      SalaryAdjustmentRequestedEvent.OutputObject
    >;

    "SalaryUpdated(address,bytes32)": TypedContractEvent<
      SalaryUpdatedEvent.InputTuple,
      SalaryUpdatedEvent.OutputTuple,
      SalaryUpdatedEvent.OutputObject
    >;
    SalaryUpdated: TypedContractEvent<
      SalaryUpdatedEvent.InputTuple,
      SalaryUpdatedEvent.OutputTuple,
      SalaryUpdatedEvent.OutputObject
    >;
  };
}
